---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-NoWindows
no_index:
  directory:
    - inc
    - t
requires:
  App::Nopaste: 0.33
  App::perlbrew: 0
  Archive::Extract: 0.60
  CatalystX::REPL: 0
  Compress::Raw::Lzma: 2.059
  Curses: 1.28
  IO::Pty: 1.10
  IO::Socket::SSL: 1.81
  IPC::ShareLite: 0
  MooseX::Daemonize: 0.15
  MooseX::Role::Cmd: 0.10
  MooseX::Workers: 0.16
  POE::Component::Client::Keepalive: 0
  Starman: 0
  Sys::SigAction: 0.15
  local::lib: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
